Repository LandvibeDev/web-chat-frontend, pull requests merged in 2020-08, with the labels that each got.

#15 [WIP] 프로젝트 초기 리액트 설정
  .env.development
  .eslintignore
  .eslintrc
  .gitignore
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/components/pages/ChatConstructor.jsx
  src/components/pages/ChatRoomDashboard.jsx
  src/components/pages/index.js
  src/index.css
  src/index.js
  src/logo.svg
  src/serviceWorker.js
  src/setupTests.js
  yarn.lock
Labels: feature

#21 채팅방 메시지 리스트 구성하기 위한 컴포넌트 추가
  .env.development
  .env.test
  .gitignore
  package.json
  src/App.js
  src/__snapshots__/storybook.test.js.snap
  src/common/MessageTarget.js
  src/common/MessageType.js
  src/components/atoms/.gitkeep
  src/components/atoms/Text.jsx
  src/components/atoms/Text.stories.jsx
  src/components/molecules/.gitkeep
  src/components/molecules/Message.jsx
  src/components/molecules/Message.stories.jsx
  src/components/organisms/.gitkeep
  src/components/organisms/Conversation.jsx
  src/components/organisms/Conversation.stories.jsx
  src/mock/chat/index.js
  src/mock/index.js
  src/pages/chat/index.js
  src/pages/chat/room/index.jsx
  src/pages/chat/room/templates/index.jsx
  src/pages/chat/room/templates/index.stories.jsx
  src/service/.gitkeep
  src/service/getMessages.js
Labels: feature

#23 Feat/deployment
  .github/workflows/web-chat-front.yml
  Dockerfile
  task-definition.json
Labels: feature

#26 메시지 보내기
  src/__snapshots__/storybook.test.js.snap
  src/common/MessageTarget.js
  src/components/atoms/Button.jsx
  src/components/atoms/Button.stories.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Input.stories.jsx
  src/components/molecules/Message.jsx
  src/components/molecules/MessageSender.jsx
  src/components/molecules/MesssageSender.stories.jsx
  src/components/organisms/MessageEditor.jsx
  src/components/organisms/MesssageEditor.stories.jsx
  src/mock/chat/index.js
  src/pages/chat/room/index.jsx
  src/pages/chat/room/templates/index.jsx
  src/pages/chat/room/templates/index.stories.jsx
  src/service/createMessages.js
Labels: feature, fix

#24 feat: 채팅방 목록 (#17)
  package-lock.json
  src/components/atoms/Button.jsx
  src/components/atoms/Text.jsx
  src/components/molecules/Card.jsx
  src/components/organisms/CardList.jsx
  src/mock/room/index.js
  src/pages/rooms/board/index.jsx
  src/pages/rooms/board/templates/index.jsx
  src/service/getRooms.js
Labels: feature

#31 메시지 데이터 응답 형식 변경 및 채팅방 생성 요청 버그 수정
  src/__snapshots__/storybook.test.js.snap
  src/components/atoms/Button.jsx
  src/components/atoms/Button.stories.jsx
  src/components/organisms/CardList.jsx
  src/pages/rooms/board/templates/index.jsx
  src/pages/rooms/board/templates/index.stories.jsx
  src/pages/rooms/maker/templates/index.jsx
  src/service/createRooms.js
  src/service/getMessages.js
Labels: enhancement, fix

#34 메시지 전송 완료 후, 메시지 리스트 다시 불러오도록 변경
  src/App.js
  src/components/atoms/Button.jsx
  src/components/atoms/Text.jsx
  src/components/atoms/Text.stories.jsx
  src/pages/chat/room/index.jsx
  src/pages/error/index.js
  src/pages/error/nomatch/index.jsx
  src/pages/error/nomatch/index.stories.jsx
Labels: feature
